import type { Difficulty, SpiceLevel, BudgetLevel, VerificationStatus, RecipeIngredient } from "./types";

export function formatMinutes(min: number): string {
  if (min < 60) return `${min} min`;
  const h = Math.floor(min / 60);
  const m = min % 60;
  return m === 0 ? `${h} hr` : `${h} hr ${m} min`;
}

export const DIFFICULTY_LABEL: Record<Difficulty, string> = {
  easy: "Easy",
  medium: "Medium",
  hard: "Involved",
};

export const SPICE_LABEL: Record<SpiceLevel, string> = {
  none: "No heat",
  mild: "Mild",
  medium: "Medium heat",
  hot: "Hot",
  very_hot: "Very hot",
};

export const SPICE_CHILLIES: Record<SpiceLevel, number> = {
  none: 0, mild: 1, medium: 2, hot: 3, very_hot: 4,
};

export const BUDGET_LABEL: Record<BudgetLevel, string> = {
  budget: "Budget-friendly",
  moderate: "Moderate cost",
  premium: "Premium",
};

export const VERIFICATION_LABEL: Record<VerificationStatus, { label: string; note: string }> = {
  ai_drafted: {
    label: "AI-drafted",
    note: "An original draft generated by our editorial AI. Not yet reviewed by a human editor — read critically and trust your cooking instincts.",
  },
  editor_needed: {
    label: "Awaiting editor",
    note: "This draft is queued for human editorial review.",
  },
  community_submitted: {
    label: "Community recipe",
    note: "Shared by a home cook in our community. Not independently verified.",
  },
  public_domain_imported: {
    label: "Public domain",
    note: "Adapted from a public-domain source, with attribution on the recipe.",
  },
  open_license_imported: {
    label: "Open license",
    note: "Imported under an open license, with attribution and license noted.",
  },
  licensed_partner: {
    label: "Partner recipe",
    note: "Provided by a licensed content partner.",
  },
  verified: {
    label: "Kitchen-verified",
    note: "Tested and verified by the Cook Anything editorial kitchen.",
  },
};

export function formatQuantity(ing: RecipeIngredient): string {
  if (ing.unit === "to_taste") return "to taste";
  if (ing.quantity === null) return ing.unit ?? "";
  const q = Number.isInteger(ing.quantity)
    ? String(ing.quantity)
    : String(Math.round(ing.quantity * 100) / 100);
  if (!ing.unit) return q;
  const unitLabel: Record<string, string> = {
    g: "g", kg: "kg", ml: "ml", l: "L", tsp: "tsp", tbsp: "tbsp", cup: ing.quantity === 1 ? "cup" : "cups",
    piece: "", whole: "whole", clove: ing.quantity === 1 ? "clove" : "cloves",
    sprig: ing.quantity === 1 ? "sprig" : "sprigs", leaf: ing.quantity === 1 ? "leaf" : "leaves",
    pinch: ing.quantity === 1 ? "pinch" : "pinches", handful: ing.quantity === 1 ? "handful" : "handfuls",
    inch: "inch", cm: "cm", slice: ing.quantity === 1 ? "slice" : "slices",
    bunch: ing.quantity === 1 ? "bunch" : "bunches", can: ing.quantity === 1 ? "can" : "cans",
  };
  const u = unitLabel[ing.unit] ?? ing.unit;
  return u ? `${q} ${u}` : q;
}

export function titleFromSlug(slug: string): string {
  return slug.split("-").map((w) => w[0]?.toUpperCase() + w.slice(1)).join(" ");
}
