import type { Allergen } from "../types";

/**
 * Cooking Companion — shared recipe, state, BYOK chat, and hosted API shapes.
 *
 * Phase 1 separates browser authority from hosted server authority. Phase 2
 * adds a conservative trust context so neither hosted nor BYOK responses can
 * silently upgrade allergen, safety, provenance or cook-test claims.
 */

export type IngredientRole =
  | "BASE"
  | "AROMATIC"
  | "ACID"
  | "HEAT"
  | "SWEET"
  | "UMAMI_SALT"
  | "THICKENER"
  | "COATING"
  | "FAT"
  | "GARNISH";

export type Criticality = "STRUCTURAL" | "FLAVOR" | "OPTIONAL";
export type HeatStability = "COOK_STABLE" | "ADD_LATE";

export interface CompanionIngredient {
  name: string;
  /** Canonical slug from the ingredient taxonomy (drives multilingual names) */
  slug: string;
  /** Tamil / Hindi names so the agent can mirror the user's vocabulary */
  ta: string | null;
  hi: string | null;
  qty: number | null;
  unit: string | null;
  role: IngredientRole;
  criticality: Criticality;
  heat_stability: HeatStability;
  /** Stage label from the recipe's stages array that consumes this ingredient */
  stage: string;
  visual_checks?: string[];
  subs?: { name: string; notes?: string }[];
  notes?: string;
}

export interface CompanionStep {
  id: string;
  stage: string;
  text: string;
  timer_minutes?: number;
}

export interface CompanionTrustContext {
  allergen_status: "derived" | "reviewed" | "incomplete" | "unknown";
  contains_allergens: Allergen[];
  cross_contact_notes: string[];
  safety_warnings: string[];
  critical_checks: string[];
  cook_test_status: "not_cook_tested" | "partially_cook_tested" | "cook_tested";
  provenance_summary: string;
  substitution_warning: string;
}

/** The recipe JSON used to ground a companion session. */
export interface CompanionRecipe {
  recipe_id: string;
  title: string;
  base_servings: number;
  spice_level: string;
  cookware: string[];
  stages: string[];
  ingredients: CompanionIngredient[];
  steps: CompanionStep[];
  trust: CompanionTrustContext;
  substitution_notes?: string;
  indian_kitchen_adaptation?: string | null;
}

/** Build-generated, server-resolved snapshot used only by hosted mode. */
export interface TrustedCompanionRecipe extends CompanionRecipe {
  /** SHA-256 of the canonical companion recipe payload. */
  version: string;
}

export interface LedgerEntry {
  original: string;
  now: string;
  qty?: string;
  constraint?: string;
  cascade?: string;
}

export interface CompanionTimer {
  label: string;
  remaining_s: number;
}

/** Maintained by the model, but accepted only after server-side validation. */
export interface CompanionState {
  recipe_id: string;
  servings: number;
  stage: string;
  steps_done: string[];
  current_step: string;
  substitution_ledger: LedgerEntry[];
  flags: string[];
  timers: CompanionTimer[];
}

/* --------------------------- BYOK chat contract -------------------------- */

export type ChatContentBlock =
  | { type: "text"; text: string }
  | {
      type: "image";
      source: { type: "base64"; media_type: string; data: string };
    };

export interface ChatMessage {
  role: "user" | "assistant";
  content: string | ChatContentBlock[];
}

/* -------------------------- Hosted API contract -------------------------- */

export interface HostedSessionCreateRequest {
  recipe_id: string;
}

export interface HostedSessionResponse {
  state: CompanionState | null;
  error?: string;
}

export interface HostedTurnRequest {
  /** Only the newest user text. Hosted image input remains disabled in Phase 1. */
  message: string;
  /** A fresh UUID generated by the browser. Duplicate ids execute at most once. */
  client_turn_id: string;
}

export interface CompanionResponse {
  reply: string;
  /** Last server-validated state; never a raw model object. */
  state: CompanionState | null;
  error?: string;
  /** Non-fatal signal that malformed model state was discarded. */
  state_warning?: "invalid_model_state";
}

export function initialCompanionState(recipe: CompanionRecipe): CompanionState {
  return {
    recipe_id: recipe.recipe_id,
    servings: recipe.base_servings,
    stage: recipe.stages[0] ?? "PREP",
    steps_done: [],
    current_step: recipe.steps[0]?.id ?? "start",
    substitution_ledger: [],
    flags: [],
    timers: [],
  };
}
